In [1]:
"""
-----------------------------------------------------------------------------
Assignment-1: Matrix computation exercise using python and numpy
-----------------------------------------------------------------------------
AUTHOR: Soumitra Samanta (soumitra.samanta@gm.rkmvu.ac.in)
-----------------------------------------------------------------------------
Package required:
Numpy: https://numpy.org/
Matplotlib: https://matplotlib.org
-----------------------------------------------------------------------------
"""

import numpy as np
from numpy.random import RandomState

from typing import Tuple

np.random.seed(42)# To reproduce the random numbers


# Generate a random vector $x \in \mathbf{R}^{n}$ contains intergers between $[-l, l]$.
[3 points]

In [2]:
n = 10
l = 9
x = []
############################################################################
#                             Your code will be here                       #
#--------------------------------------------------------------------------#
def generate_random_vector(min,max,length):
    return np.random.randint(min,max+1,length)
x=generate_random_vector(-l,l,n)
#--------------------------------------------------------------------------#
#                             End of your code                             #
############################################################################

print('A random vector of size {}: ' .format(n))
print('-'*70)
print('x: {}' .format(x))
print('-'*70)

A random vector of size 10: 
----------------------------------------------------------------------
x: [-3  5  1 -2 -3  9  1  1 -6 -2]
----------------------------------------------------------------------


# Write a function to calculate the 'dot' product between two vectors. Generate two random vectors $x, y \in \mathbf{R}^{n}$ contains intergers between $[-l, l]$ and find the dot product between $x$ and $y$ (your function should handle different order vectors). Check your result with the [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).
[5 points]




In [6]:
n = 10
l = 9
x = []
y = []

def vector_dot_product(
    x: np.array,
    y: np.array,
)->float:
    """
    Dot product between two vectors
    
    Inputs:
        - x: 1st vector
        - y: 2nd vector
       
    Output:
        - val: Dot product between x and y
    
    """
    
    val = []
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    if len(x)==len(y):
        sum=0
        for i in range(len(x)):
            sum+=x[i]*y[i]
        val=float(sum)

        
        d=np.dot(x,y)
        print(f'Result of numpy.dot is {d}')
        
        if val==d:
            print("dot product is matching with result of .dot")
        else:
            print("dot product is not matching with .dot")
    else:
        print("Dot product is not possible ")
        val=None
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return val

# np.random.seed(42)# for reproduce the random numbers
x = generate_random_vector(-l,l,n)
y = generate_random_vector(-l,l,n)

print('Two random vectors of size {} are:' .format(n))
print('-'*70)
print('x: {}\nand \ny: {}' .format(x, y))
print('-'*70)

val = vector_dot_product(x, y)
print('The dot product between x and y is: {}' .format(val))
print('-'*70)

Two random vectors of size 10 are:
----------------------------------------------------------------------
x: [-9  2 -2  1  9  7 -2 -7 -7 -9]
and 
y: [-5  0 -3 -1 -3 -1 -2  2 -8 -9]
----------------------------------------------------------------------
Result of numpy.dot is 143
dot product is matching with result of .dot
The dot product between x and y is: 143.0
----------------------------------------------------------------------


# Generate a random matrix $A$ of size $m \times n$ contains intergers between $[-l, l]$.
[2 points]

In [4]:
m = 3
n = 5
l = 9
A = []
############################################################################
#                             Your code will be here                       #
#--------------------------------------------------------------------------#
def mXn_matrix_generator(min, max ,row,col):
    return np.array([np.random.randint(min,max+1,col) for _ in range(row)])
A=mXn_matrix_generator(-l,l,m,n)
#--------------------------------------------------------------------------#
#                             End of your code                             #
############################################################################

print('A random matrix of size {}x{} A:\n{}: ' .format(m, n, A))
print('-'*70)



A random matrix of size 3x5 A:
[[-3  8 -6  4  8]
 [-1 -8  5 -3  2]
 [-2  5 -7  4  7]]: 
----------------------------------------------------------------------


# Write a function to calculate the product of two matrices. Generate two random matrices $x \in \mathbf{R}^{m \times n}$ and $y \in \mathbf{R}^{n \times m}$ contains intergers between $[-l, l]$ and find the product of of $x$ and $y$ (your function should handle different order matrices). Check your result with the [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) or [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).

[10 points]




In [5]:
m = 3
n = 5
l = 9
x = []
y = []

def matrix_multiplication(
    x: np.array,
    y: np.array,
)->np.array:
    """
    Dot product between two vectors
    
    Inputs:
        - x: 1st matrix
        - y: 2nd matrix
       
    Output:
        - val: multiplication x and y
    
    """
    
    val = []
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    if len(x[0])!=len(y):
        return f'Not Possible'
    else:
        val=np.zeros([len(x),len(y[0])], int)
        for i in range(len(x)):  
            for j in range(len(y[0])):  
                for k in range(len(y)):  
                    val[i][j] += x[i][k] * y[k][j] 
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return val

# np.random.seed(42)# for reproduce the random numbers
A = mXn_matrix_generator(-l,l,m,n)
B = mXn_matrix_generator(-l,l,n,m)

print('Two random matrices are:')
print('A: \n{}\nand\nB: \n{}' .format(A, B))
print('-'*70)

val = matrix_multiplication(A, B)
print('The multiplication of A and B using my function is: \n{}' .format(val))
print('-'*70)

val1 = np.matmul(A, B)
print('The multiplication of A and B using numpy.matmul is: \n{}' .format(val1))
print('-'*70)

val1 = np.dot(A, B)
print('The multiplication of A and B using numpy.dot is: \n{}' .format(val1))
print('-'*70)


Two random matrices are:
A: 
[[-6  8 -2 -6 -8]
 [-4  0 -6  8  2]
 [-8  0 -6  4  6]]
and
B: 
[[ 5 -2  4]
 [-2  6  3]
 [ 8  5  3]
 [-1  5  3]
 [-9 -3 -1]]
----------------------------------------------------------------------
The multiplication of A and B using my function is: 
[[  16   44  -16]
 [ -94   12  -12]
 [-146  -12  -44]]
----------------------------------------------------------------------
The multiplication of A and B using numpy.matmul is: 
[[  16   44  -16]
 [ -94   12  -12]
 [-146  -12  -44]]
----------------------------------------------------------------------
The multiplication of A and B using numpy.dot is: 
[[  16   44  -16]
 [ -94   12  -12]
 [-146  -12  -44]]
----------------------------------------------------------------------
