In [1]:
import numpy as np

In [5]:
x=np.arange(24).reshape((4,2,3))
x

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [14]:
y=np.arange(6).reshape((2,3))#from rule 1
x+y

array([[[ 0,  2,  4],
        [ 6,  8, 10]],

       [[ 6,  8, 10],
        [12, 14, 16]],

       [[12, 14, 16],
        [18, 20, 22]],

       [[18, 20, 22],
        [24, 26, 28]]])

In [11]:
y=np.arange(30).reshape((5,2,3)) #from rule3 
x+y

ValueError: operands could not be broadcast together with shapes (4,2,3) (5,2,3) 

In [13]:
y=np.arange(8).reshape((4,2,1))#from rule 2
x+y

array([[[ 0,  1,  2],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [12, 13, 14]],

       [[16, 17, 18],
        [20, 21, 22]],

       [[24, 25, 26],
        [28, 29, 30]]])

In [17]:
y=np.arange(10).reshape((5,2,1))#from rule 3
x+y

ValueError: cannot reshape array of size 10 into shape (4,2,1)

In [33]:
x=np.arange(6).reshape((3,2))
y=np.arange(3)
print(y)
y1=y[:,np.newaxis]
x+y1

[0 1 2]


array([[0, 1],
       [3, 4],
       [6, 7]])

In [93]:
points=np.random.randint(1,10,400).reshape((200,2),order='F')
points

array([[1, 6],
       [2, 1],
       [4, 5],
       [4, 7],
       [6, 2],
       [3, 6],
       [8, 1],
       [1, 9],
       [6, 4],
       [1, 4],
       [7, 3],
       [6, 3],
       [6, 6],
       [2, 2],
       [5, 7],
       [1, 1],
       [1, 8],
       [4, 1],
       [5, 8],
       [2, 5],
       [1, 4],
       [1, 1],
       [1, 7],
       [3, 1],
       [6, 8],
       [7, 9],
       [3, 3],
       [2, 3],
       [2, 8],
       [5, 8],
       [4, 4],
       [3, 6],
       [4, 4],
       [8, 2],
       [2, 4],
       [3, 1],
       [8, 3],
       [2, 1],
       [1, 9],
       [4, 3],
       [6, 2],
       [4, 6],
       [3, 7],
       [5, 2],
       [1, 5],
       [7, 3],
       [3, 2],
       [4, 2],
       [3, 7],
       [2, 5],
       [8, 6],
       [1, 1],
       [4, 4],
       [8, 7],
       [1, 9],
       [7, 6],
       [7, 3],
       [8, 2],
       [8, 7],
       [7, 2],
       [7, 1],
       [3, 4],
       [4, 1],
       [1, 4],
       [2, 6],
       [2, 7],
       [1,

In [106]:
centroids=np.array([[10,11],[9,12],[3,6]])
# points=np.array([[1,2],[3,4],[7,2],[10,3]])
points=np.random.randint(1,10,400).reshape((200,2),order='F')
# dist=np.sqrt(np.sum((centroids[0]-points)**2,axis=1))
# dist

centroids_=centroids[:,np.newaxis,:]
# dist_=np.sqrt(np.sum((centroids_-points)**2,axis=2))
dist_=(centroids_-points)
# print(dist_)

dist=[]

for i in range(centroids.shape[0]):
    dist_i=centroids[i]-points
    dist.append(dist_i)
# print(np.array(dist))

compare=dist_-dist
print(compare)


[[[0 0]
  [0 0]
  [0 0]
  ...
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ...
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ...
  [0 0]
  [0 0]
  [0 0]]]


In [133]:
c_p_dist_=np.sqrt(np.sum((centroids_-points)**2,axis=2))
# print(c_p_dist_)
min_index=np.argmin(c_p_dist_,axis=0)
s=set(min_index)
s

{0, 1, 2}

In [129]:
group_A=points[min_index==0]
group_B=points[min_index==1]
group_C=points[min_index==2]
c1=np.sum(group_A,axis=0)/group_A.shape[0]
print(c1)
c2=np.sum(group_B,axis=0)/group_B.shape[0]
print(c2)
c3=np.sum(group_C,axis=0)/group_C.shape[0]
print(c3)

for i in range(len(min_index)):
    points[min_index==i]

[5.   5.15]
[1.66666667 4.        ]
[5.05649718 5.47457627]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
