In [92]:
import numpy as np
x=np.random.randint(0,20,size=(100,1))
y=np.random.randint(0,10,size=(100,1))
# A=np.concatenate((x,y),axis=1)
A=np.block([x,y])
# print(A)
B=A[0]
C=B-A

D=C**2

x=np.round(np.sqrt(D[:,0]+D[:,1]),3)
# print(x.reshape(100,1))

In [93]:
print(A)

[[18  1]
 [ 2  1]
 [15  8]
 [ 6  7]
 [ 0  3]
 [14  1]
 [ 1  2]
 [ 3  9]
 [ 3  4]
 [14  8]
 [ 4  2]
 [17  5]
 [ 1  0]
 [11  3]
 [ 8  3]
 [15  9]
 [ 3  6]
 [ 4  4]
 [17  3]
 [17  5]
 [14  2]
 [17  0]
 [10  9]
 [ 6  4]
 [ 9  5]
 [ 5  4]
 [ 0  9]
 [12  7]
 [19  0]
 [14  7]
 [13  9]
 [ 7  8]
 [10  2]
 [ 3  5]
 [11  2]
 [ 4  0]
 [ 3  2]
 [ 4  2]
 [ 1  4]
 [16  5]
 [13  8]
 [ 2  1]
 [10  4]
 [ 6  4]
 [19  3]
 [ 4  8]
 [18  5]
 [ 7  7]
 [16  8]
 [ 4  0]
 [ 6  1]
 [ 1  0]
 [ 2  2]
 [17  2]
 [10  5]
 [ 3  8]
 [17  4]
 [15  3]
 [18  0]
 [11  1]
 [11  4]
 [ 1  9]
 [ 8  6]
 [ 3  7]
 [ 7  5]
 [ 8  6]
 [11  2]
 [ 6  4]
 [17  6]
 [ 8  7]
 [19  4]
 [16  2]
 [ 9  2]
 [ 1  2]
 [14  1]
 [ 4  2]
 [18  9]
 [18  2]
 [ 5  7]
 [18  1]
 [15  4]
 [ 7  6]
 [ 0  2]
 [ 0  1]
 [ 4  7]
 [ 1  3]
 [ 3  8]
 [ 1  2]
 [12  9]
 [18  8]
 [ 8  0]
 [ 0  9]
 [11  4]
 [ 8  8]
 [14  6]
 [ 8  7]
 [16  5]
 [ 3  1]
 [15  3]
 [ 0  2]]


In [94]:
ran_points=np.array([A[0],A[1],A[2],A[3],A[4]])
print(ran_points)
centroids=np.array([[3,4],[7,8]])
print(centroids[0])

distance1=(centroids[0]-ran_points)**2
print(distance1)
distance2=(centroids[1]-ran_points)**2
print(distance2)
s=np.empty(shape=(2,5),dtype=int)
# print(s[0][0])



for i in range(distance1.shape[0]):
    s[0][i]=distance1[i][0]+distance1[i][1]
for i in range(distance2.shape[0]):
    s[1][i]=distance2[i][0]+distance2[i][1]
    
s


[[18  1]
 [ 2  1]
 [15  8]
 [ 6  7]
 [ 0  3]]
[3 4]
[[225   9]
 [  1   9]
 [144  16]
 [  9   9]
 [  9   1]]
[[121  49]
 [ 25  49]
 [ 64   0]
 [  1   1]
 [ 49  25]]


array([[234,  10, 160,  18,  10],
       [170,  74,  64,   2,  74]])

In [100]:
f=[]
for i in range(s.shape[1]):
    f.append(np.argmin(s[:,i]))
ac=np.array(f)
ac

array([1, 0, 1, 1, 0])

In [102]:
#argmin
l=[12,30,56,5]
np.argmin(l)

3