In [2]:
import numpy as np

In [3]:
x=np.arange(1,13,1).reshape(3,4)
print(x)
print(np.sum(x,axis=1))
print(np.sum(x,axis=0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 26 42]
[15 18 21 24]


In [4]:
x=np.arange(1,13,1).reshape(2,2,3)
print(x)
print(np.sum(x,axis=2))
print(np.sum(x,axis=1))
print(np.sum(x,axis=0))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 6 15]
 [24 33]]
[[ 5  7  9]
 [17 19 21]]
[[ 8 10 12]
 [14 16 18]]


In [5]:
x=x[np.newaxis,:,:,:]

In [6]:


print(x)
print(np.sum(x,axis=3))
print(np.sum(x,axis=2))
print(np.sum(x,axis=1))
print(np.sum(x,axis=0))

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]
[[[ 6 15]
  [24 33]]]
[[[ 5  7  9]
  [17 19 21]]]
[[[ 8 10 12]
  [14 16 18]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
x=np.arange(1,13,1).reshape(3,4)

In [8]:
print(x%2==0)#boolean mask array#same shape of original
x[x%2==0]#1D (6,) array of true vals
print((x%2==0) | (x%5==0))
print(x[(x%2==0) | (x%5==0)])

[[False  True False  True]
 [False  True False  True]
 [False  True False  True]]
[[False  True False  True]
 [ True  True False  True]
 [False  True False  True]]
[ 2  4  5  6  8 10 12]


In [15]:
x=np.arange(1,10,1).reshape(3,3)
x
print(x)
print(x[[False,True,False]])
x[[False,True,False]].shape
print(x[[True,True,True],[2,1,0]])
x[[0,1,2],[2,1,0]]
x


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]]
[3 5 7]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
print(x[x%2])
print(x[x%2,np.ones((1,3),dtype=int)])
print(x[x%2,np.array([0,1,2])])

[[[4 5 6]
  [1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]
  [1 2 3]]

 [[4 5 6]
  [1 2 3]
  [4 5 6]]]
[[5 2 5]
 [2 5 2]
 [5 2 5]]
[[4 2 6]
 [1 5 3]
 [4 2 6]]


In [11]:
x[:,[[2],[1],[0]]]

array([[[3],
        [2],
        [1]],

       [[6],
        [5],
        [4]],

       [[9],
        [8],
        [7]]])

In [12]:
x=np.array([[0,2],[2,1]])
x[[0,1],[True,False]]

array([0, 2])

In [13]:
x[[2,0,1],[2,0,1]]

IndexError: index 2 is out of bounds for axis 0 with size 2