In [33]:
import numpy as np

In [38]:
x=np.arange(1,13,1).reshape(3,4)
print(x)
print(np.sum(x,axis=1))
print(np.sum(x,axis=0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 26 42]
[15 18 21 24]


[[False  True False  True]
 [False  True False  True]
 [False  True False  True]]
[[False  True False  True]
 [ True  True False  True]
 [False  True False  True]]
[ 2  4  5  6  8 10 12]


In [32]:
x=np.arange(1,13,1).reshape(2,2,3)
print(x)
print(np.sum(x,axis=2))
print(np.sum(x,axis=1))
print(np.sum(x,axis=0))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 6 15]
 [24 33]]
[[ 5  7  9]
 [17 19 21]]
[[ 8 10 12]
 [14 16 18]]


In [30]:
x=x[np.newaxis,:,:,:]

In [31]:


print(x)
print(np.sum(x,axis=3))
print(np.sum(x,axis=2))
print(np.sum(x,axis=1))
print(np.sum(x,axis=0))

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]
[[[ 6 15]
  [24 33]]]
[[[ 5  7  9]
  [17 19 21]]]
[[[ 8 10 12]
  [14 16 18]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [49]:
x=np.arange(1,13,1).reshape(3,4)

In [50]:
print(x%2==0)#boolean mask array#same shape of original
x[x%2==0]#1D (6,) array of true vals
print((x%2==0) | (x%5==0))
print(x[(x%2==0) | (x%5==0)])

[[False  True False  True]
 [False  True False  True]
 [False  True False  True]]
[[False  True False  True]
 [ True  True False  True]
 [False  True False  True]]
[ 2  4  5  6  8 10 12]


In [104]:
x=np.arange(1,10,1).reshape(3,3)
x
print(x)
x[[False,True,False]]
x[[False,True,False]].shape
x[[True,True,True],[2,1,0]]
x[[0,1,2],[2,1,0]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([3, 5, 7])

In [108]:
print(x[x%2])
print(x[x%2,np.ones((1,3),dtype=int)])
print(x[x%2,np.array([0,1,2])])

[[[4 5 6]
  [1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]
  [1 2 3]]

 [[4 5 6]
  [1 2 3]
  [4 5 6]]]
[[5 2 5]
 [2 5 2]
 [5 2 5]]
[[4 2 6]
 [1 5 3]
 [4 2 6]]


In [101]:
x[:,[[2],[1],[0]]]

array([[[3],
        [2],
        [1]],

       [[6],
        [5],
        [4]],

       [[9],
        [8],
        [7]]])

In [91]:
x=np.array([[0,2],[2,1]])
x[[0,1],[True,False]]

array([0, 2])

In [94]:
x[:,[2,0]]

IndexError: index 2 is out of bounds for axis 1 with size 2