In [1]:
"""
-----------------------------------------------------------------------------
Assignment-2: Matrix computation exercise using python and numpy
-----------------------------------------------------------------------------
AUTHOR: Soumitra Samanta (soumitra.samanta@gm.rkmvu.ac.in)
-----------------------------------------------------------------------------
Package required:
Numpy: https://numpy.org/
Matplotlib: https://matplotlib.org
-----------------------------------------------------------------------------
"""

import numpy as np
from numpy.random import RandomState

from typing import Tuple

np.random.seed(42)# To reproduce the random numbers


# Generate a random vector $x \in \mathbf{R}^{n}$ contains intergers between $[-l, l]$.
[3 points]

In [2]:
n = 10
l = 9
x = []
############################################################################
#                             Your code will be here                       #
#--------------------------------------------------------------------------#
for i in range(n):
    x.append(np.random.randint(-l,l))
#--------------------------------------------------------------------------#
#                             End of your code                             #
############################################################################

print('A random vector of size {}: ' .format(n))
print('-'*70)
print('x: {}' .format(x))
print('-'*70)

A random vector of size 10: 
----------------------------------------------------------------------
x: [-3, 5, 1, -2, -3, 1, 1, -6, -2, -7]
----------------------------------------------------------------------


# Write a function to calculate the 'dot' product between two vectors. Generate two random vectors $x, y \in \mathbf{R}^{n}$ contains intergers between $[-l, l]$ and find the dot product between $x$ and $y$ (your function should handle different order vectors). Check your result with the [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).
[5 points]




In [3]:
n = 10
l = 9
x = []
y = []

def vector_dot_product(
    x: np.array,
    y: np.array,
)->float:
    """
    Dot product between two vectors
    
    Inputs:
        - x: 1st vector
        - y: 2nd vector
       
    Output:
        - val: Dot product between x and y
    
    """
    
    val = []
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    sum=0
    for i in range(n):
        sum+=x[i]*y[i]
    sum2=np.dot(x,y)
    if sum == sum2:
        print("My function is right...")
        val=sum
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return val

# np.random.seed(42)# for reproduce the random numbers
x = []
y = []
for i in range(n):
    x.append(np.random.randint(-l,l))
for i in range(n):
    y.append(np.random.randint(-l,l))
print('Two random vectors of size {} are:' .format(n))
print('-'*70)
print('x: {}\nand \ny: {}' .format(x, y))
print('-'*70)

val = vector_dot_product(x, y)
print('The dot product between x and y is: {}' .format(val))
print('-'*70)

Two random vectors of size 10 are:
----------------------------------------------------------------------
x: [-8, 2, -4, -8, -9, 2, 2, 7, 0, 6]
and 
y: [5, 5, 2, -7, -5, -3, -1, -3, 8, -6]
----------------------------------------------------------------------
My function is right...
The dot product between x and y is: -2
----------------------------------------------------------------------


# Generate a random matrix $A$ of size $m \times n$ contains intergers between $[-l, l]$.
[2 points]

In [4]:
m = 3
n = 5
l = 9
A = []
############################################################################
#                             Your code will be here                       #
#--------------------------------------------------------------------------#
A = np.array([[np.random.randint(-l,l) for _ in range(n)] for _ in range(m)])
#--------------------------------------------------------------------------#
#                             End of your code                             #
############################################################################

print('A random matrix of size {}x{} A:\n{}: ' .format(m, n, A))
print('-'*70)



A random matrix of size 3x5 A:
[[ 4  8 -1 -8  5]
 [-3  2 -2  5 -7]
 [ 4  7 -6  8 -2]]: 
----------------------------------------------------------------------


# Write a function to calculate the product of two matrices. Generate two random matrices $x \in \mathbf{R}^{m \times n}$ and $y \in \mathbf{R}^{n \times m}$ contains intergers between $[-l, l]$ and find the product of of $x$ and $y$ (your function should handle different order matrices). Check your result with the [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) or [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).

[10 points]




In [5]:
m = 3
n = 5
l = 9
x = []
y = []

def matrix_multiplication(
    x: np.array,
    y: np.array,
)->np.array:
    """
    Dot product between two vectors
    
    Inputs:
        - x: 1st matrix
        - y: 2nd matrix
       
    Output:
        - val: multiplication x and y
    
    """
    
    val = []
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    for i in range(len(x)):
        val1 = []
        for j in range(len(y[0])):
            sum = 0
            for k in range(len(y)):
                sum+= x[i][k]*y[k][j]
            val1.append(sum)
        val.append(val1)
    val = np.array(val)    
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return val

# np.random.seed(42)# for reproduce the random numbers
A = []
B = []
A = [[np.random.randint(-l,l) for _ in range(n)]for _ in range(m)]
B = [[np.random.randint(-l,l) for _ in range(m)]for _ in range(n)]
A = np.array(A)
B = np.array(B)
print('Two random matrices are:')
print('A: \n{}\nand\nB: \n{}' .format(A, B))
print('-'*70)

val = matrix_multiplication(A, B)
print('The multiplication of A and B using my function is: \n{}' .format(val))
print('-'*70)

val1 = np.matmul(A, B)
print('The multiplication of A and B using numpy.matmul is: \n{}' .format(val1))
print('-'*70)

val1 = np.dot(A, B)
print('The multiplication of A and B using numpy.dot is: \n{}' .format(val1))
print('-'*70)


Two random matrices are:
A: 
[[-6 -8 -4  0 -6]
 [ 8  2 -8  0 -6]
 [ 4  6  5 -2  4]]
and
B: 
[[-2  6  3]
 [ 8  5  3]
 [-1  5  3]
 [-9 -3 -1]
 [-9  2 -2]]
----------------------------------------------------------------------
The multiplication of A and B using my function is: 
[[   6 -108  -42]
 [  62    6   18]
 [  17   93   39]]
----------------------------------------------------------------------
The multiplication of A and B using numpy.matmul is: 
[[   6 -108  -42]
 [  62    6   18]
 [  17   93   39]]
----------------------------------------------------------------------
The multiplication of A and B using numpy.dot is: 
[[   6 -108  -42]
 [  62    6   18]
 [  17   93   39]]
----------------------------------------------------------------------


# Implement elementary row operations and check your script with a random example.
[15 points]

In [17]:
def elementary_ops_interchange_rows(
    A: np.array, 
    ith_row: int, 
    jth_row: int
)->np.array:
    """
    Elementary row operation: interchange i-th and j-th rows
    
     Inputs:
        - A: Given matrix
        - ith_row: i-th row
        - jth_row: j-th row
        
    Output:
        - A: Resultant rows interchhanged matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    for k in range(len(A[0])):
        temp=A[ith_row-1][k]
        A[ith_row-1][k]=A[jth_row-1][k]
        A[jth_row-1][k]=temp
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A


def elementary_ops_scale_row(
    A: np.array, 
    ith_row: int, 
    scalar_val: float
)->np.array:
    """
    Elementary row operation: Scaling i-th row  with the scalar_val value
    
     Inputs:
        - A: Given matrix
        - ith_row: row want to scale
        - scalar_val: scalar value
        
    Output:
        - A: Resultant row scaling matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    for j in range(len(A[0])):
        if A[ith_row-1][j] != 0:
            A[ith_row-1][j]*=scalar_val
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A

def elementary_ops_change_row(
    A: np.array, 
    ith_row: int, 
    jth_row: int,
    scalar_val: float
)->np.array:
    """
    Elementary row operation: Change i-th based on i<-i + scalar_val*j
    
     Inputs:
        - A: Given matrix
        - ith_row: i-th row
        - jth_row: j-th row
        - scalar_val: scalar value
        
    Output:
        - A: Resultant row updated matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    B = elementary_ops_scale_row(A.copy(), jth_row, scalar_val)
    for k in range(len(A[0])):
        A[ith_row-1][k]+=B[jth_row-1][k] 
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A

def elementary_ops_interchange_rows_mult(
    A: np.array, 
    ith_row: int, 
    jth_row: int
)->Tuple[np.array, np.array]:
    """
    Elementary row operation: interchange i-th and j-th rows
    
     Inputs:
        - A: Given matrix
        - ith_row: i-th row
        - jth_row: j-th row
        
    Output:
        - A: Resultant rows interchhanged matrix
    """
    I = []
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    I= np.eye(m)
    I = elementary_ops_interchange_rows(I, ith_row, jth_row)
    A = matrix_multiplication(I, A)
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A, I


def elementary_ops_scale_row_mult(
    A: np.array, 
    ith_row: int, 
    scalar_val: float
)->Tuple[np.array, np.array]:
    """
    Elementary row operation: Scaling i-th row  with the scalar_val value
    
     Inputs:
        - A: Given matrix
        - ith_row: row want to scale
        - scalar_val: scalar value
        
    Output:
        - A: Resultant row scaling matrix
    """
    
    I = []
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    I= np.eye(m)
    I = elementary_ops_scale_row(I, ith_row, scalar_val)
    A = matrix_multiplication(I, A)      
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A, I

def elementary_ops_change_row_mult(
    A: np.array, 
    ith_row: int, 
    jth_row: int,
    scalar_val: float
)->Tuple[np.array, np.array]:
    """
    Elementary row operation: Change i-th based on i<-i + scalar_val*j
    
     Inputs:
        - A: Given matrix
        - ith_row: i-th row
        - jth_row: j-th row
        - scalar_val: scalar value
        
    Output:
        - A: Resultant row updated matrix
    """
    
    I = []
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    I = np.eye(m)
    I = elementary_ops_change_row(I, ith_row, jth_row, scalar_val)
    A = matrix_multiplication(I, A)
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A, I




np.random.seed(42)# for reproduce the random numbers
m = 3
n = 5
A = []

A = np.array([[np.random.randint(-l,l)for _ in range(n)]for _ in range(m)])

print('A random matrices A:\n{}' .format(A))
print('-'*70)
i = 1
j = 2
scalar = 3
E_ij = elementary_ops_interchange_rows(A.copy(), i, j)
print('Elementary row operation: interchange {}-th and {}-th rows on A: \n{}\nis: \n{}' .format(i, j, A, E_ij))
print('-'*70)

E_i = elementary_ops_scale_row(A.copy(), i, scalar)
print('Elementary row operation: Scaling {}-th row  with the {} value on A: \n{}\nis: \n{}' .format(i, scalar, A, E_i))
print('-'*70)

E_ij_scalar = elementary_ops_change_row(A.copy(), i, j, scalar)
print('Elementary row operation: Change {}-th based on {}<-{} + {}*{} on A: \n{}\nis: \n{}' .format(i, i, i, scalar, j, A, E_ij_scalar))
print('-'*70)

E_ij, I_ij = elementary_ops_interchange_rows_mult(A.copy(), i, j)
print('Elementary row operation (multiplication): interchange {}-th and {}-th rows on A: \n{}\nis: \n{}\nand I_ij: \n{}' .format(i, j, A, E_ij, I_ij))
print('-'*70)

E_i, I_i = elementary_ops_scale_row_mult(A.copy(), i, scalar)
print('Elementary row operation(multiplication): Scaling {}-th row  with the {} value on A: \n{}\nis: \n{}\nand I_i: \n{}' .format(i, scalar, A, E_i, I_i))
print('-'*70)

E_ij_scalar, I_ij_scalar = elementary_ops_change_row_mult(A.copy(), i, j, scalar)
print('Elementary row operation(multiplication): Change {}-th based on {}<-{} + {}*{} on A: \n{}\nis: \n{}\nand I_ij(scale): \n{}' .format(i, i, i, scalar, j, A, E_ij_scalar, I_ij_scalar))
print('-'*70)



A random matrices A:
[[-3  5  1 -2 -3]
 [ 1  1 -6 -2 -7]
 [-8  2 -4 -8 -9]]
----------------------------------------------------------------------
Elementary row operation: interchange 1-th and 2-th rows on A: 
[[-3  5  1 -2 -3]
 [ 1  1 -6 -2 -7]
 [-8  2 -4 -8 -9]]
is: 
[[ 1  1 -6 -2 -7]
 [-3  5  1 -2 -3]
 [-8  2 -4 -8 -9]]
----------------------------------------------------------------------
Elementary row operation: Scaling 1-th row  with the 3 value on A: 
[[-3  5  1 -2 -3]
 [ 1  1 -6 -2 -7]
 [-8  2 -4 -8 -9]]
is: 
[[-9 15  3 -6 -9]
 [ 1  1 -6 -2 -7]
 [-8  2 -4 -8 -9]]
----------------------------------------------------------------------
Elementary row operation: Change 1-th based on 1<-1 + 3*2 on A: 
[[-3  5  1 -2 -3]
 [ 1  1 -6 -2 -7]
 [-8  2 -4 -8 -9]]
is: 
[[  0   8 -17  -8 -24]
 [  1   1  -6  -2  -7]
 [ -8   2  -4  -8  -9]]
----------------------------------------------------------------------
Elementary row operation (multiplication): interchange 1-th and 2-th rows on A: 
[[

# Implement elementary column operations and check your script with random example
[10 points]

In [19]:
def elementary_ops_interchange_cols(
    A: np.array, 
    ith_col: int, 
    jth_col: int
)->np.array:
    """
    Elementary col operation: interchange i-th and j-th cols
    
     Inputs:
        - A: Given matrix
        - ith_col: i-th col
        - jth_col: j-th col
        
    Output:
        - A: Resultant cols interchhanged matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    for k in range(len(A)):
        temp=A[k][ith_col-1]
        A[k][ith_col-1]=A[k][jth_col-1]
        A[k][jth_col-1]=temp
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A


def elementary_ops_scale_col(
    A: np.array, 
    ith_col: int, 
    scalar_val: float
)->np.array:
    """
    Elementary col operation: Scaling i-th col  with the scalar_val value
    
     Inputs:
        - A: Given matrix
        - ith_col: col want to scale
        - scalar_val: scalar value
        
    Output:
        - A: Resultant col scaling matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    for j in range(len(A)):
        A[j][ith_col-1]*=scalar_val
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A

def elementary_ops_change_col(
    A: np.array, 
    ith_col: int, 
    jth_col: int,
    scalar_val: float
)->np.array:
    """
    Elementary col operation: Change i-th col based on i<-i + scalar_val*j
    
     Inputs:
        - A: Given matrix
        - ith_col: i-th col
        - jth_col: j-th col
        - scalar_val: scalar value
        
    Output:
        - A: Resultant col updated matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    B = elementary_ops_scale_col(np.copy(A), jth_col, scalar_val)
    for k in range(len(A)):
        A[k][ith_col-1]+=B[k][jth_col-1]

            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A

def elementary_ops_interchange_cols_mult(
    A: np.array, 
    ith_col: int, 
    jth_col: int
)->np.array:
    """
    Elementary col operation: interchange i-th and j-th cols
    
     Inputs:
        - A: Given matrix
        - ith_col: i-th col
        - jth_col: j-th col
        
    Output:
        - A: Resultant cols interchhanged matrix
    """
    
    I = []
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    I = np.eye(n)
    I = elementary_ops_interchange_rows(I, ith_col, jth_col)
    A = matrix_multiplication(A, I)
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A, I


def elementary_ops_scale_col_mult(
    A: np.array, 
    ith_col: int, 
    scalar_val: float
)->Tuple[np.array, np.array]:
    """
    Elementary col operation: Scaling i-th col  with the scalar_val value
    
     Inputs:
        - A: Given matrix
        - ith_col: col want to scale
        - scalar_val: scalar value
        
    Output:
        - A: Resultant col scaling matrix
    """
    
    I = []
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    I = np.eye(n)
    I = elementary_ops_scale_row(I, ith_col, scalar_val)
    A = matrix_multiplication(A, I)
    
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A, I

def elementary_ops_change_col_mult(
    A: np.array, 
    ith_col: int, 
    jth_col: int,
    scalar_val: float
)->Tuple[np.array, np.array]:
    """
    Elementary col operation: Change i-th col based on i<-i + scalar_val*j
    
     Inputs:
        - A: Given matrix
        - ith_col: i-th col
        - jth_col: j-th col
        - scalar_val: scalar value
        
    Output:
        - A: Resultant col updated matrix
    """
    
    I = []
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    I = np.eye(n)
    I = elementary_ops_change_row(I, jth_col, ith_col, scalar_val)
    A = matrix_multiplication(A, I)
    

            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A, I


np.random.seed(42)# for reproduce the random numbers
m = 3
n = 5
A = []
A = np.array([[np.random.randint(-l,l)for _ in range(n)]for _ in range(m)])

print('A random matrices A:\n{}' .format(A))
print('-'*70)
i = 1
j = 2
scalar = 3
E_ij = elementary_ops_interchange_cols(np.copy(A), i, j)
print('Elementary col operation: interchange {}-th and {}-th cols on A: \n{}' .format(i, j, E_ij))
print('-'*70)

E_i = elementary_ops_scale_col(np.copy(A), i, scalar)
print('Elementary col operation: Scaling {}-th col  with the {} value on A: \n{}' .format(i, scalar, E_i))
print('-'*70)

E_ij_scalar = elementary_ops_change_col(np.copy(A), i, j, scalar)
print('Elementary col operation: Change {}-th based on {}<-{} + {}*{} on A: \n{}' .format(i, i, i, scalar, j, E_ij_scalar))
print('-'*70)

E_ij, I_ij = elementary_ops_interchange_cols_mult(np.copy(A), i, j)
print('Elementary col operation (multiplication): interchange {}-th and {}-th cols on A: \n{}\nis: \n{}\nand I_ij: \n{}' .format(i, j, A, E_ij, I_ij))
print('-'*70)

E_i, I_i = elementary_ops_scale_col_mult(np.copy(A), i, scalar)
print('Elementary col operation (multiplication): Scaling {}-th col  with the {} value on A: \n{}\nis: \n{}\nand I_i: \n{}' .format(i, scalar, A, E_i, I_i))
print('-'*70)

E_ij_scalar, I_ij_scalar = elementary_ops_change_col_mult(np.copy(A), i, j, scalar)
print('Elementary col operation (multiplication): Change {}-th based on {}<-{} + {}*{} on A: \n{}\nis: \n{}\nand I_ij_scalar: \n{}' .format(i, i, i, scalar, j, A, E_ij_scalar, I_ij_scalar))
print('-'*70)


A random matrices A:
[[-3  5  1 -2 -3]
 [ 1  1 -6 -2 -7]
 [-8  2 -4 -8 -9]]
----------------------------------------------------------------------
Elementary col operation: interchange 1-th and 2-th cols on A: 
[[ 5 -3  1 -2 -3]
 [ 1  1 -6 -2 -7]
 [ 2 -8 -4 -8 -9]]
----------------------------------------------------------------------
Elementary col operation: Scaling 1-th col  with the 3 value on A: 
[[ -9   5   1  -2  -3]
 [  3   1  -6  -2  -7]
 [-24   2  -4  -8  -9]]
----------------------------------------------------------------------
Elementary col operation: Change 1-th based on 1<-1 + 3*2 on A: 
[[12  5  1 -2 -3]
 [ 4  1 -6 -2 -7]
 [-2  2 -4 -8 -9]]
----------------------------------------------------------------------
Elementary col operation (multiplication): interchange 1-th and 2-th cols on A: 
[[-3  5  1 -2 -3]
 [ 1  1 -6 -2 -7]
 [-8  2 -4 -8 -9]]
is: 
[[ 5. -3.  1. -2. -3.]
 [ 1.  1. -6. -2. -7.]
 [ 2. -8. -4. -8. -9.]]
and I_ij: 
[[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 

# Implement row and column sweep out and check your script with random example
[10 points]

In [8]:
def sweep_out_row(
    A: np.array,
    ith_row: int,
    pivot_element: Tuple[int, int]
)->np.array:
    """
    Sweep out a i-th row based on the given pivot element
    
    Inputs:
        - A: Given matrix
        - ith_row: row to sweep out
        - pivot_element pivot element
        
    Output:
        - A: Resultant row sweep out matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    A = elementary_ops_scale_col(np.array(A,dtype = float), pivot_element[1], 1 / A[pivot_element[0]-1, pivot_element[1]-1])
    for i in range(len(A[0])):
        if i != pivot_element[1]-1:
            A = elementary_ops_change_col(A, i+1, pivot_element[1], -A[pivot_element[0]-1, i])
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return A
    
def sweep_out_row_mult(
    A: np.array,
    ith_row: int,
    pivot_element: Tuple[int, int]
)->np.array:
    """
    Sweep out a i-th row based on the given pivot element
    
    Inputs:
        - A: Given matrix
        - ith_row: row to sweep out
        - pivot_element pivot element
        
    Output:
        - A: Resultant row sweep out matrix
    """
    
    E_ops = []
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    E_ops = np.eye(len(A[0]))
    B = elementary_ops_scale_row(E_ops.copy(), pivot_element[1], 1 / A[pivot_element[0]-1, pivot_element[1]-1])
    A = matrix_multiplication(A, B)
    for i in range(len(A[0])):
        if i != pivot_element[1]-1:
            B = elementary_ops_change_row(E_ops.copy(), pivot_element[1], i+1, -A[pivot_element[0]-1, i])
            A = matrix_multiplication(A, B)
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return A, E_ops
    
    
def sweep_out_col(
    A: np.array,
    ith_col: int,
    pivot_element: Tuple[int, int]
)->np.array:
    """
    Sweep out a i-th column based on the given pivot element
    
    Inputs:
        - A: Given matrix
        - ith_col: column to sweep out
        - pivot_element pivot element
        
    Output:
        - A: Resultant column sweep out matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    A = elementary_ops_scale_row(np.array(A,dtype = float), pivot_element[0], 1 / A[pivot_element[0]-1, pivot_element[1]-1])
    for i in range(len(A)):
        if i != pivot_element[0]-1:
            A = elementary_ops_change_row(A, i+1, pivot_element[0], -A[i, pivot_element[1]-1])
        
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return A

def sweep_out_col_mult(
    A: np.array,
    ith_col: int,
    pivot_element: Tuple[int, int]
)->Tuple[np.array, np.array]:
    """
    Sweep out a i-th column based on the given pivot element
    
    Inputs:
        - A: Given matrix
        - ith_col: column to sweep out
        - pivot_element pivot element
        
    Output:
        - A: Resultant column sweep out matrix
        - E_ops: Product of all the elementary operations
    """
    
    E_ops = []
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    E_ops = np.eye(len(A))
    B = elementary_ops_scale_row(E_ops.copy(), pivot_element[0], 1 / A[pivot_element[0]-1, pivot_element[1]-1])
    A = matrix_multiplication(B, A)
    for i in range(len(A)):
        if i != pivot_element[0]-1:
            B = elementary_ops_change_row(E_ops.copy(), i+1, pivot_element[0], -A[i, pivot_element[1]-1])
            A = matrix_multiplication(B, A)
    
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return A, E_ops




np.random.seed(42)# for reproduce the random numbers
m = 3
n = 5
A = []
A = np.array([[np.random.randint(-l,l) for _ in range(n)]for _ in range(m)])
print('A random matrices A:\n{}' .format(A))
print('-'*70)
i = 1
j = 2
scalar = 3
E_ij = sweep_out_row(np.copy(A), i, (i, j))
print('{}-th row sweep out based on ({}, {}) as pivot on A: \n{}\nis : \n{}' .format(i, i, j, A, E_ij))
print('-'*70)

E_ij, E_ops = sweep_out_row_mult(np.copy(A), i, (i, j))
print('{}-th row sweep out (multiplication) based on ({}, {}) as pivot on A: \n{}\nis: \n{}\nand product of all the elementary operations E_ops: \n{}' .format(i, i, j, A, E_ij, E_ops))
print('-'*70)

E_ij = sweep_out_col(np.copy(A), j, (i, j))
print('{}-th col sweep out based on ({}, {}) as pivot on A: \n{}' .format(j, i, j, E_ij))
print('-'*70)

E_ij, E_ops = sweep_out_col_mult(np.copy(A), j, (i, j))
print('{}-th col sweep out (multiplication) based on ({}, {}) as pivot on A: \n{}\n is : \n{}\nand product of all the elementary operations E_ops: \n{}' .format(j, i, j, A, E_ij, E_ops))
print('-'*70)




A random matrices A:
[[-3  5  1 -2 -3]
 [ 1  1 -6 -2 -7]
 [-8  2 -4 -8 -9]]
----------------------------------------------------------------------
1-th row sweep out based on (1, 2) as pivot on A: 
[[-3  5  1 -2 -3]
 [ 1  1 -6 -2 -7]
 [-8  2 -4 -8 -9]]
is : 
[[ 0.   1.   0.   0.   0. ]
 [ 1.6  0.2 -6.2 -1.6 -6.4]
 [-6.8  0.4 -4.4 -7.2 -7.8]]
----------------------------------------------------------------------
1-th row sweep out (multiplication) based on (1, 2) as pivot on A: 
[[-3  5  1 -2 -3]
 [ 1  1 -6 -2 -7]
 [-8  2 -4 -8 -9]]
is: 
[[ 0.   1.   0.   0.   0. ]
 [ 1.6  0.2 -6.2 -1.6 -6.4]
 [-6.8  0.4 -4.4 -7.2 -7.8]]
and product of all the elementary operations E_ops: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
----------------------------------------------------------------------
2-th col sweep out based on (1, 2) as pivot on A: 
[[-0.6  1.   0.2 -0.4 -0.6]
 [ 1.6  0.  -6.2 -1.6 -6.4]
 [-6.8  0.  -4.4 -7.2 -7.8]]
---------------------

# Implement echelon form of a matrix $A$ 
[20 points]

In [13]:
def reduced_echelon_form(
    A: np.array
)-> np.array:
    """Reduction to echelon form of a matrix.
    
    Inputs:
        - A: Given matrix
        
    Output:
        - A: Echelon form of A
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    r=0
    for i in range(len(A[0])):
        for j in range(r,len(A)):
            if A[j][i]!=0:
                k = A[j][i]
                A = elementary_ops_interchange_rows(A, r+1, j+1)
                A = elementary_ops_scale_row(A, r+1, 1/k)
                for l in range(r+1,len(A)):
                    m = A[l][i] 
                    if m != 0:
                        A = elementary_ops_change_row(A, l+1, r+1, m*(-1))
                r+=1
                j = len(A)
                break
                        
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A
        
    
np.random.seed(42)# for reproduce the random numbers
m = 4
n = 5
A = []
A = np.array([
    [0, 0, 0, 0, 5],
    [0, 2, -1, 3, -2],
    [0, -4, 2, -6, 4],
    [0, 6, -3, 8, 1]
]).astype(float)

print('A random matrices A:\n{}' .format(A))
print('-'*70)

EF_A = reduced_echelon_form(A) 
print('The reduced echelon form of A:\n{} ' .format(np.round(EF_A, 3)))
print('-'*70)
        
    

A random matrices A:
[[ 0.  0.  0.  0.  5.]
 [ 0.  2. -1.  3. -2.]
 [ 0. -4.  2. -6.  4.]
 [ 0.  6. -3.  8.  1.]]
----------------------------------------------------------------------
The reduced echelon form of A:
[[ 0.   1.  -0.5  1.5 -1. ]
 [ 0.   0.   0.   1.  -7. ]
 [ 0.   0.   0.   0.   1. ]
 [ 0.   0.   0.   0.   0. ]] 
----------------------------------------------------------------------


# [<font color='red'>BONUS</font>] Implement reduction to upper triangular form of a matrix $A$
[5 points]

In [10]:

def reduced_upper_triangular_form(
    A: np.array
)-> np.array:
    """Reduction to upper triangular form of a square matrix.
    
    Inputs:
        - A: Given matrix
        
    Output:
        - A: Upper triangular form of A
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    for i in range(len(A)-1):
        for j in range(i+1,len(A)):
            if A[j][i] != 0:
                r = A[i,i]
                k = A[j,i]
                A = elementary_ops_change_row(np.array(A,dtype = float), j+1, i+1, -k / r)
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A

np.random.seed(42)# for reproduce the random numbers
n = 5
A = []
A = np.array([[np.random.randint(-l,l) for _ in range(n)]for _ in range(n)])
print('A random matrices A:\n{}' .format(A))
print('-'*70)

UT_A = reduced_upper_triangular_form(A)        
print('The reduced upper triangular form of A:\n{} ' .format(np.round(UT_A, 3)))
print('-'*70)      






A random matrices A:
[[-3  5  1 -2 -3]
 [ 1  1 -6 -2 -7]
 [-8  2 -4 -8 -9]
 [ 2  2  7  0  6]
 [ 5  5  2 -7 -5]]
----------------------------------------------------------------------
The reduced upper triangular form of A:
[[ -3.      5.      1.     -2.     -3.   ]
 [  0.      2.667  -5.667  -2.667  -8.   ]
 [  0.      0.    -30.75  -14.    -35.   ]
 [  0.      0.      0.     -4.65   -1.626]
 [  0.     -0.      0.      0.     -2.378]] 
----------------------------------------------------------------------
