In [45]:
import numpy as np
import pandas as pd


In [65]:
x=np.random.randint(1,10,(3,6))
print(x)
print(x[:,1:2])
R=x[1]-x
print(R)

[[3 5 5 1 5 6]
 [6 9 7 7 6 6]
 [4 4 1 4 5 6]]
[[5]
 [9]
 [4]]
[[3 4 2 6 1 0]
 [0 0 0 0 0 0]
 [2 5 6 3 1 0]]


In [47]:
Grocery_data=pd.read_csv('Supermart_Grocery.csv')
Grocery_data.head()

Order ID Customer Name          Category      Sub Category         City  \
0      OD1        Harish      Oil & Masala           Masalas      Vellore   
1      OD2         Sudha         Beverages     Health Drinks  Krishnagiri   
2      OD3       Hussain       Food Grains      Atta & Flour   Perambalur   
3      OD4       Jackson  Fruits & Veggies  Fresh Vegetables   Dharmapuri   
4      OD5       Ridhesh       Food Grains   Organic Staples         Ooty   

   Order Date Region  Sales  Discount  Profit       State  
0  11-08-2017  North   1254      0.12  401.28  Tamil Nadu  
1  11-08-2017  South    749      0.18  149.80  Tamil Nadu  
2  06-12-2017   West   2360      0.21  165.20  Tamil Nadu  
3  10-11-2016  South    896      0.25   89.60  Tamil Nadu  
4  10-11-2016  South   2355      0.26  918.45  Tamil Nadu

In [48]:
nad={'Category':'Oil & Masala',
     'Sub Category':'Health Drinks'}
Grocery_data=pd.read_csv('Supermart_Grocery.csv',na_values=nad)
Grocery_data

Order ID Customer Name           Category      Sub Category         City  \
0         OD1        Harish                NaN           Masalas      Vellore   
1         OD2         Sudha          Beverages               NaN  Krishnagiri   
2         OD3       Hussain        Food Grains      Atta & Flour   Perambalur   
3         OD4       Jackson   Fruits & Veggies  Fresh Vegetables   Dharmapuri   
4         OD5       Ridhesh        Food Grains   Organic Staples         Ooty   
...       ...           ...                ...               ...          ...   
9989   OD9990        Sudeep  Eggs, Meat & Fish              Eggs      Madurai   
9990   OD9991          Alan             Bakery          Biscuits  Kanyakumari   
9991   OD9992          Ravi        Food Grains              Rice         Bodi   
9992   OD9993          Peer                NaN            Spices   Pudukottai   
9993   OD9994        Ganesh        Food Grains      Atta & Flour  Tirunelveli   

      Order Date Region  Sales  Discount  Profit       State  
0     11-08-2017  North   1254      0.12  401.28  Tamil Nadu  
1     11-08-2017  South    749      0.18  149.80  Tamil Nadu  
2     06-12-2017   West   2360      0.21  165.20  Tamil Nadu  
3     10-11-2016  South    896      0.25   89.60  Tamil Nadu  
4     10-11-2016  South   2355      0.26  918.45  Tamil Nadu  
...          ...    ...    ...       ...     ...         ...  
9989  12/24/2015   West    945      0.16  359.10  Tamil Nadu  
9990  07-12-2015   West   1195      0.26   71.70  Tamil Nadu  
9991  06-06-2017   West   1567      0.16  501.44  Tamil Nadu  
9992  10/16/2018   West   1659      0.15  597.24  Tamil Nadu  
9993   4/17/2018   West   1034      0.28  165.44  Tamil Nadu  

[9994 rows x 11 columns]

In [49]:
Grocery_data.dtypes

Order ID          object
Customer Name     object
Category          object
Sub Category      object
City              object
Order Date        object
Region            object
Sales              int64
Discount         float64
Profit           float64
State             object
dtype: object

In [50]:
Grocery_data['Order Date']=Grocery_data['Order Date'].str.replace('/','-')

In [61]:
Grocery_data['Profit']=Grocery_data['Profit'].astype(np.float32)
Grocery_data['Discount']=Grocery_data['Discount'].astype(np.float32)

Grocery_data['Order Date']=pd.to_datetime(Grocery_data['Order Date'])
# Grocery_data['Order Date']=Grocery_data['Order Date'].astype(np.datetime64)
Grocery_data.dtypes


Order ID                 object
Customer Name            object
Category                 object
Sub Category             object
City                     object
Order Date       datetime64[ns]
Region                   object
Sales                     int64
Discount                float32
Profit                  float32
State                    object
dtype: object