In [19]:

import numpy as np 

features=np.random.randint(1,10,(10,3))
class_data=np.random.randint(1,3,(10,1))
main_data=np.block([features,class_data])
print(main_data)
test=np.array([1,2,3])
print(test)
def KNN(data,given):
    distance=np.sqrt(np.sum((given-data[:,:-1])**2,axis=1))
    print(distance)
    t5=np.argsort(distance)[:5]
    print(t5)
    count_of_class=np.bincount(data[t5,3])
    print(count_of_class)
    return np.argmax(count_of_class)
KNN(main_data,test)

[[9 1 5 2]
 [8 1 4 1]
 [1 5 4 1]
 [9 1 3 1]
 [9 6 4 2]
 [1 4 4 1]
 [4 3 9 1]
 [6 5 1 1]
 [4 6 6 2]
 [6 8 2 2]]
[1 2 3]
[8.30662386 7.14142843 3.16227766 8.06225775 9.         2.23606798
 6.78232998 6.164414   5.83095189 7.87400787]
[5 2 8 7 6]
[0 4 1]


1