In [1]:
import numpy as np
import pandas as pd


In [2]:
x=np.random.randint(1,10,(3,6))
print(x)
print(x[:,1:2])
R=x[1]-x
print(R)

[[1 5 1 6 7 3]
 [9 9 7 1 5 1]
 [2 9 7 9 3 3]]
[[5]
 [9]
 [9]]
[[ 8  4  6 -5 -2 -2]
 [ 0  0  0  0  0  0]
 [ 7  0  0 -8  2 -2]]


In [3]:
Grocery_data=pd.read_csv('Supermart_Grocery.csv')
Grocery_data.head()

Order ID Customer Name          Category      Sub Category         City   
0      OD1        Harish      Oil & Masala           Masalas      Vellore  \
1      OD2         Sudha         Beverages     Health Drinks  Krishnagiri   
2      OD3       Hussain       Food Grains      Atta & Flour   Perambalur   
3      OD4       Jackson  Fruits & Veggies  Fresh Vegetables   Dharmapuri   
4      OD5       Ridhesh       Food Grains   Organic Staples         Ooty   

   Order Date Region  Sales  Discount  Profit       State  
0  11-08-2017  North   1254      0.12  401.28  Tamil Nadu  
1  11-08-2017  South    749      0.18  149.80  Tamil Nadu  
2  06-12-2017   West   2360      0.21  165.20  Tamil Nadu  
3  10-11-2016  South    896      0.25   89.60  Tamil Nadu  
4  10-11-2016  South   2355      0.26  918.45  Tamil Nadu

In [4]:
nad={'Category':'Oil & Masala',
     'Sub Category':'Health Drinks'}
Grocery_data=pd.read_csv('Supermart_Grocery.csv',na_values=nad)
Grocery_data

Order ID Customer Name           Category      Sub Category         City   
0         OD1        Harish                NaN           Masalas      Vellore  \
1         OD2         Sudha          Beverages               NaN  Krishnagiri   
2         OD3       Hussain        Food Grains      Atta & Flour   Perambalur   
3         OD4       Jackson   Fruits & Veggies  Fresh Vegetables   Dharmapuri   
4         OD5       Ridhesh        Food Grains   Organic Staples         Ooty   
...       ...           ...                ...               ...          ...   
9989   OD9990        Sudeep  Eggs, Meat & Fish              Eggs      Madurai   
9990   OD9991          Alan             Bakery          Biscuits  Kanyakumari   
9991   OD9992          Ravi        Food Grains              Rice         Bodi   
9992   OD9993          Peer                NaN            Spices   Pudukottai   
9993   OD9994        Ganesh        Food Grains      Atta & Flour  Tirunelveli   

      Order Date Region  Sales  Discount  Profit       State  
0     11-08-2017  North   1254      0.12  401.28  Tamil Nadu  
1     11-08-2017  South    749      0.18  149.80  Tamil Nadu  
2     06-12-2017   West   2360      0.21  165.20  Tamil Nadu  
3     10-11-2016  South    896      0.25   89.60  Tamil Nadu  
4     10-11-2016  South   2355      0.26  918.45  Tamil Nadu  
...          ...    ...    ...       ...     ...         ...  
9989  12/24/2015   West    945      0.16  359.10  Tamil Nadu  
9990  07-12-2015   West   1195      0.26   71.70  Tamil Nadu  
9991  06-06-2017   West   1567      0.16  501.44  Tamil Nadu  
9992  10/16/2018   West   1659      0.15  597.24  Tamil Nadu  
9993   4/17/2018   West   1034      0.28  165.44  Tamil Nadu  

[9994 rows x 11 columns]

In [5]:
Grocery_data.dtypes

Order ID          object
Customer Name     object
Category          object
Sub Category      object
City              object
Order Date        object
Region            object
Sales              int64
Discount         float64
Profit           float64
State             object
dtype: object

In [6]:
Grocery_data['Order Date']=Grocery_data['Order Date'].str.replace('/','-')

In [7]:
Grocery_data['Profit']=Grocery_data['Profit'].astype(np.float32)
Grocery_data['Discount']=Grocery_data['Discount'].astype(np.float32)

Grocery_data['Order Date']=pd.to_datetime(Grocery_data['Order Date'])
# Grocery_data['Order Date']=Grocery_data['Order Date'].astype(np.datetime64)
Grocery_data.dtypes


Order ID                 object
Customer Name            object
Category                 object
Sub Category             object
City                     object
Order Date       datetime64[ns]
Region                   object
Sales                     int64
Discount                float32
Profit                  float32
State                    object
dtype: object

In [9]:
Grocery_data.head(10)

Order ID Customer Name          Category      Sub Category            City   
0      OD1        Harish               NaN           Masalas         Vellore  \
1      OD2         Sudha         Beverages               NaN     Krishnagiri   
2      OD3       Hussain       Food Grains      Atta & Flour      Perambalur   
3      OD4       Jackson  Fruits & Veggies  Fresh Vegetables      Dharmapuri   
4      OD5       Ridhesh       Food Grains   Organic Staples            Ooty   
5      OD6        Adavan       Food Grains   Organic Staples      Dharmapuri   
6      OD7         Jonas  Fruits & Veggies  Fresh Vegetables          Trichy   
7      OD8         Hafiz  Fruits & Veggies      Fresh Fruits  Ramanadhapuram   
8      OD9         Hafiz            Bakery          Biscuits     Tirunelveli   
9     OD10      Krithika            Bakery             Cakes         Chennai   

  Order Date Region  Sales  Discount      Profit       State  
0 2017-11-08  North   1254      0.12  401.279999  Tamil Nadu  
1 2017-11-08  South    749      0.18  149.800003  Tamil Nadu  
2 2017-06-12   West   2360      0.21  165.199997  Tamil Nadu  
3 2016-10-11  South    896      0.25   89.599998  Tamil Nadu  
4 2016-10-11  South   2355      0.26  918.450012  Tamil Nadu  
5 2015-06-09   West   2305      0.26  322.700012  Tamil Nadu  
6 2015-06-09   West    826      0.33  346.920013  Tamil Nadu  
7 2015-06-09   West   1847      0.32  147.759995  Tamil Nadu  
8 2015-06-09   West    791      0.23  181.929993  Tamil Nadu  
9 2015-06-09   West   1795      0.27  484.649994  Tamil Nadu

In [13]:
Grocery_data.isnull().sum()

Order ID            0
Customer Name       0
Category         1361
Sub Category      719
City                0
Order Date          0
Region              0
Sales               0
Discount            0
Profit              0
State               0
dtype: int64