In [4]:

import numpy as np 

features=np.random.randint(1,10,(10,3))
class_data=np.random.randint(0,2,(10,1))
main_data=np.block([features,class_data])
print(main_data)
test=np.array([1,2,3])
print(test)
def KNN(data,given):
    distance=np.sqrt(np.sum((given-data[:,:-1])**2,axis=1))
    print(distance)
    t5=np.argsort(distance)[:5]
    print(t5)
    count_of_class=np.bincount(data[t5,3])
    print(count_of_class)
    if count_of_class[0]<count_of_class[1]:
        return "Yes"
    else:
        return "No"
KNN(main_data,test)

[[4 6 2 1]
 [7 3 2 1]
 [9 1 1 0]
 [7 9 8 1]
 [1 9 1 0]
 [8 4 6 1]
 [6 4 6 0]
 [5 3 9 0]
 [7 4 9 0]
 [8 1 9 0]]
[1 2 3]
[ 5.09901951  6.164414    8.30662386 10.48808848  7.28010989  7.87400787
  6.164414    7.28010989  8.71779789  9.2736185 ]
[0 1 6 4 7]
[3 2]


'No'