In [2]:
import numpy as np

In [5]:
x=np.array([10,3,2,7,9,5])
np.argsort(x)

array([10,  3,  2,  7,  9,  5])

In [4]:
np.bincount(x)

array([0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1])

In [39]:
features=np.random.randint(1,10,(10,3))
features
class_data=np.random.randint(0,2,(10,1))
class_data
data=np.block([features,class_data])
print(data)
print(np.delete(data,data[:,3]))

[[1 1 4 1]
 [4 7 1 1]
 [5 4 6 0]
 [5 3 7 1]
 [5 9 9 0]
 [6 4 5 1]
 [5 5 7 1]
 [4 8 6 1]
 [4 7 5 0]
 [1 1 2 1]]
[4 1 4 7 1 1 5 4 6 0 5 3 7 1 5 9 9 0 6 4 5 1 5 5 7 1 4 8 6 1 4 7 5 0 1 1 2
 1]


In [ ]:
given=np.array([1,2,3])
given-

# Pandas