In [21]:

import numpy as np 

features=np.random.randint(1,10,(10,3))
class_data=np.random.randint(1,3,(10,1))
main_data=np.block([features,class_data])
print(main_data)
test=np.array([1,2,3])
print(test)
def KNN(data,given):
    distance=np.sqrt(np.sum((given-data[:,:-1])**2,axis=1))
    print(distance)
    t5=np.argsort(distance)[:5]
    print(t5)
    count_of_class=np.bincount(data[t5,3])
    print(count_of_class)
    return np.argmax(count_of_class)
KNN(main_data,test)

[[9 5 8 1]
 [1 5 3 1]
 [1 5 9 1]
 [2 2 1 2]
 [9 5 3 1]
 [6 9 5 1]
 [1 8 5 1]
 [3 5 2 2]
 [7 7 8 1]
 [4 7 5 2]]
[1 2 3]
[9.89949494 3.         6.70820393 2.23606798 8.54400375 8.83176087
 6.32455532 3.74165739 9.2736185  6.164414  ]
[3 1 7 9 6]
[0 2 3]


2