In [4]:

import numpy as np 

features=np.random.randint(1,10,(10,3))
class_data=np.random.randint(1,3,(10,1))
main_data=np.block([features,class_data])
print(main_data)
test=np.array([1,2,3])
print(test)
def KNN(data,given):
    distance=np.sqrt(np.sum((given-data[:,:-1])**2,axis=1))
    print(distance)
    t5=np.argsort(distance)[:5]
    print(t5)
    count_of_class=np.bincount(data[t5,3])
    print(count_of_class)
    return np.argmax(count_of_class)
KNN(main_data,test)

[[3 6 6 1]
 [5 3 7 1]
 [2 9 6 1]
 [8 3 7 1]
 [7 4 2 2]
 [7 9 4 1]
 [2 2 8 1]
 [2 7 6 1]
 [6 7 3 2]
 [1 6 3 2]]
[1 2 3]
[5.38516481 5.74456265 7.68114575 8.1240384  6.40312424 9.2736185
 5.09901951 5.91607978 7.07106781 4.        ]
[9 6 0 1 7]
[0 4 1]


1

In [9]:
main_data[:,:3]

array([[3, 6, 6],
       [5, 3, 7],
       [2, 9, 6],
       [8, 3, 7],
       [7, 4, 2],
       [7, 9, 4],
       [2, 2, 8],
       [2, 7, 6],
       [6, 7, 3],
       [1, 6, 3]])