In [1]:
"""
-----------------------------------------------------------------------------
Assignment-4: Matrix computation exercise using python and numpy
-----------------------------------------------------------------------------
AUTHOR: Soumitra Samanta (soumitra.samanta@gm.rkmvu.ac.in)
-----------------------------------------------------------------------------
Package required:
Numpy: https://numpy.org/
Matplotlib: https://matplotlib.org
-----------------------------------------------------------------------------
"""

import numpy as np
from numpy.random import RandomState
from assignment_4_matrix_computation_exc import *

# for auto-reloading extenrnal modules
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2


# Please check the file <font color='red'>assignment_4_matrix_computation.py</font> and fillup all the functions implementation from Assignment-2 & Assignment-3.
-----------------------------------------------------------------------------

# Reduce a square matrix $A$ of order $n$ to Hermite cannonical form (HCF) by elementary row operations only. Implement your funtion as <font color='red'>reduce_to_hcf_matrix</font> started at <font color='red'>line no 735</font> in <font color='red'>assignment_4_matrix_computation.py</font> file in appropriate location. You'll find <font color='red'>assignment_4_matrix_computation.py</font> within this folder.
[20 points]

In [2]:

# Now test your code
np.random.seed(42)# for reproduce the random numbers
l = 9
n = 5
error_decimal = 10
A = []
A = np.random.randint(-l,l,size =(n,n))
print('A random matrices A:\n{}' .format(A))
print('-'*70)

A_hcf,  E_ops= reduce_to_hcf_matrix(A)        
print('The reduce to HCF of A:\n{}\nand\nE_ops: \n{} ' .format(np.round(A_hcf, error_decimal), np.round(E_ops, error_decimal)))
print('-'*70)   




A random matrices A:
[[-3  5  1 -2 -3]
 [ 1  1 -6 -2 -7]
 [-8  2 -4 -8 -9]
 [ 2  2  7  0  6]
 [ 5  5  2 -7 -5]]
----------------------------------------------------------------------
The reduce to HCF of A:
[[ 1.          0.          0.          0.02468354  0.        ]
 [ 0.          1.          0.          1.01455696  0.        ]
 [ 0.          0.          1.         -1.59493671  0.        ]
 [ 0.          0.          0.         -1.72151899  0.        ]
 [ 0.          0.          0.          0.          0.        ]]
and
E_ops: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 
----------------------------------------------------------------------


# Apply the above HCF method to find a soluation of a system $Ax=b$. Where $A$ is a matrix of order $m \times n$. You have to generate a random system of linear equation ($m$-equations with $n$ unknowns) and check your results. Use your previous funtion <font color='red'>generate_random_linear_system</font> to generate the linear system and implement <font color='red'>soln_m_equations_n_unknowns</font> started at <font color='red'>line no 766</font> in <font color='red'>assignment_4_matrix_computation.py</font> file in appropriate location. You'll find <font color='red'>assignment_4_matrix_computation.py</font> within this folder.
[10 points]

In [3]:
np.random.seed(42)# for reproduce the random numbers
l = 9
m = 4
n = 5
error_decimal = 10

A, b, x = generate_random_linear_system(m, n)
print('The coefficient matrix A: \n{}' .format(A))
print('-'*70) 
print('Right-hand vector b: \n{}' .format(b))
print('-'*70)
print('Actual soluation x: \n{}' .format(x))
print('-'*70)


x_est, HCF_A = soln_m_equations_n_unknowns(A, b)        
print('Estimated soluation x_est: \n{}\nand \nabsolute diff|x-x_est| upto {}-th decimal place: \n{}' .format(np.round(x_est, 3), error_decimal, np.round(np.abs(x-x_est), error_decimal)))
print('-'*70)      






The coefficient matrix A: 
[[-2.25827786  8.11285752  4.17589095  1.77585272 -6.19166447]
 [-6.19209863 -7.95449498  6.59117062  1.82007021  3.7453064 ]
 [-8.6294791   8.45837734  5.98396753 -5.17789601 -5.72715059]
 [-5.69871882 -3.52363963  0.44561577 -1.22498966 -3.75787548]]
----------------------------------------------------------------------
Right-hand vector b: 
[[-72.19139229]
 [  7.15082104]
 [-77.66587005]
 [ 15.6427342 ]]
----------------------------------------------------------------------
Actual soluation x: 
[[ 2.01335211]
 [-6.48911051]
 [-3.74139633]
 [-2.40548682]
 [-0.79074028]]
----------------------------------------------------------------------
Estimated soluation x_est: 
[[ 0.578]
 [-5.732]
 [-5.023]
 [-1.321]
 [ 0.171]]
and 
absolute diff|x-x_est| upto 10-th decimal place: 
[[1.43559748]
 [0.7568489 ]
 [1.28129755]
 [1.08404715]
 [0.96205706]]
----------------------------------------------------------------------


c:\Users\biswajit\Downloads\assignment_4_matrix_computation_exc.py:648: RuntimeWarning: divide by zero encountered in double_scalars
  B = elementary_ops_scale_row(E_ops.copy(), pivot_element[0], 1 / A[pivot_element[0]-1, pivot_element[1]-1])
c:\Users\biswajit\Downloads\assignment_4_matrix_computation_exc.py:111: RuntimeWarning: invalid value encountered in double_scalars
  sum=sum+x[i][k]*y[k][j]


# Use a suitable matrix reduced form (RCF, UTF, NF, HCF...) to find the $determinant$ of a square matrix of order $n$. You generate a random random square matrix of different order  and check your results with the [numpy.linalg.det](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html). Implement your funtion <font color='red'>determinant_matrix</font> started at <font color='red'>line no 797</font> in <font color='red'>assignment_4_matrix_computation.py</font> file in appropriate location. You'll find <font color='red'>assignment_4_matrix_computation.py</font> within this folder.
[10 points]

In [4]:

# Now test your code
np.random.seed(42)# for reproduce the random numbers
l = 9
n = 5
error_decimal = 10
A = []
A = np.random.randint(-l,l,size =(n,n))
print('A random matrices A:\n{}' .format(A))
print('-'*70)

det_value = determinant_matrix(A)    
det_value_numpy = np.linalg.det(A)
print('The determinant value of A using my implementarion is:\n{}\nand\nUsing numpy: \n{}\nError: {} ' .format(det_value, det_value_numpy, det_value - det_value_numpy))
print('-'*70)   




A random matrices A:
[[-3  5  1 -2 -3]
 [ 1  1 -6 -2 -7]
 [-8  2 -4 -8 -9]
 [ 2  2  7  0  6]
 [ 5  5  2 -7 -5]]
----------------------------------------------------------------------
The determinant value of A using my implementarion is:
2719.9999999999986
and
Using numpy: 
2720.000000000002
Error: -3.183231456205249e-12 
----------------------------------------------------------------------


# Implement Cramer's rule to find a soluation of a system $Ax=b$. Where $A$ is a matrix of order $n \times n$. You have to generate a random system of linear equation ($n$-equations with $n$ unknowns) and check your results. Use your previous funtion <font color='red'>generate_random_linear_system</font> to generate the linear system and implement <font color='red'>soln_n_equations_n_unknowns_cramers_rule</font> started at <font color='red'>line no 825</font> in <font color='red'>assignment_4_matrix_computation.py</font> file in appropriate location. You'll find <font color='red'>assignment_4_matrix_computation.py</font> within this folder.
[10 points]

In [5]:
np.random.seed(42)# for reproduce the random numbers
l = 9
n = 5
error_decimal = 10

A, b, x = generate_random_linear_system(n, n)
print('The coefficient matrix A: \n{}' .format(A))
print('-'*70) 
print('Right-hand vector b: \n{}' .format(b))
print('-'*70)
print('Actual soluation x: \n{}' .format(x))
print('-'*70)


x_est = soln_n_equations_n_unknowns_cramers_rule(A, b)        
print('Estimated soluation x_est: \n{}\nand \nabsolute diff|x-x_est| upto {}-th decimal place: \n{}' .format(np.round(x_est, 3), error_decimal, np.round(np.abs(x-x_est), error_decimal)))
print('-'*70)      






The coefficient matrix A: 
[[-2.25827786  8.11285752  4.17589095  1.77585272 -6.19166447]
 [-6.19209863 -7.95449498  6.59117062  1.82007021  3.7453064 ]
 [-8.6294791   8.45837734  5.98396753 -5.17789601 -5.72715059]
 [-5.69871882 -3.52363963  0.44561577 -1.22498966 -3.75787548]
 [ 2.01335211 -6.48911051 -3.74139633 -2.40548682 -0.79074028]]
----------------------------------------------------------------------
Right-hand vector b: 
[[ -0.87709288]
 [-14.6439692 ]
 [-50.34564536]
 [ 18.55121064]
 [ 46.90963557]]
----------------------------------------------------------------------
Actual soluation x: 
[[ 5.13316731]
 [-5.40587192]
 [ 0.25621989]
 [ 1.66346224]
 [-8.16389257]]
----------------------------------------------------------------------
Estimated soluation x_est: 
[[ 5.133]
 [-5.406]
 [ 0.256]
 [ 1.663]
 [-8.164]]
and 
absolute diff|x-x_est| upto 10-th decimal place: 
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
----------------------------------------------------------------------
