## Welcome to code

In [1]:
import numpy as np

In [2]:
myArr=np.array([[3,4,58,6]],np.int8)

In [3]:
myArr[0,1]

4

In [4]:
myArr.dtype

dtype('int8')

In [5]:
myArr[0,1]=66

In [6]:
myArr

array([[ 3, 66, 58,  6]], dtype=int8)

# Array Creation: conversion from other pyhton structures

# $\color{red}{\text{ciao}}$
## <font color='green'>text</font>

In [7]:
listArr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
listArr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
listArr.shape

(3, 3)

In [10]:
listArr.size

9

In [11]:
listArr.dtype

dtype('int32')

In [12]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

In [13]:
zeros=np.zeros((2,5)) ##makes array of 2,5 size

In [14]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
zeros.dtype

dtype('float64')

In [16]:
zeros[0,1]

0.0

In [17]:
rng= np.arange(15) ##makes array with elements 0 to n-1

In [18]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
lineSpace= np.linspace(1,5,12) ##12 elements between 1-5

In [20]:
lineSpace


array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [21]:
l=np.linspace(0,50,5)

In [22]:
l

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [23]:
emp=np.empty((4,6)) ## makes an array full of garbage value

In [24]:
emp

array([[6.23042070e-307, 3.56043053e-307, 1.60219306e-306,
        9.79054228e-307, 1.69119330e-306, 4.45044989e-307],
       [6.23047163e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 1.86921143e-306],
       [6.23061763e-307, 8.90104239e-307, 6.89804132e-307,
        9.34605716e-307, 1.37962456e-306, 1.42418172e-306],
       [8.06609645e-308, 6.89810244e-307, 1.22387550e-307,
        2.22522596e-306, 8.34423917e-308, 9.79107193e-307]])

In [25]:
emp_like= np.empty_like(l)

In [26]:
emp_like

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [27]:
ide = np.identity(45) ##makes an identity matrix of 45x45

In [28]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [29]:
ide.shape

(45, 45)

In [30]:
arr = np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr= arr.reshape(3,33)

In [33]:
arr.reshape(3,31) ##Error

ValueError: cannot reshape array of size 99 into shape (3,31)

In [ ]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
arr=arr.ravel() ##maked a 2d arr to 1d arr

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.shape

(99,)

In [ ]:
arr.shape()

TypeError: 'tuple' object is not callable

In [ ]:
x= [[1,2,3],[4,5,6],[7,1,0]]

In [ ]:
x

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [ ]:
ar = np.array(x)

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
ar.sum()

29

In [ ]:
a=[1,2,3]
b=[1,2,3]
na= np.array(a)
nb= np.array(b)
d=np.dot(a,b)
d

14

In [ ]:
ar.sum(axis=0)

array([12,  8,  9])

In [ ]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [ ]:
ar.T ##Transposes Arrya

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [ ]:
ar.flat

In [ ]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [ ]:
ar.ndim## no. of dimensions 

2

In [ ]:
ar.size ##no of elements

9

In [ ]:
ar.nbytes

36

In [ ]:
one = np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
one.argmax() ##maxElement At index...

8

In [ ]:
one.argmin() ##minElement At index...

0

In [ ]:
one.argsort() ## sorted order of elements according to index

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [ ]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [ ]:
ar.argmin()

8

In [ ]:
ar.argmax()

6

In [ ]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [ ]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [ ]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [ ]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [ ]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [ ]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
ar2=np.array([[1,2,1],[4,0,6],[8,1,0]])

In [ ]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [ ]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [ ]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [ ]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [ ]:
ar.sum()

29

In [ ]:
ar.max()

7

In [ ]:
ar.min()

0

In [ ]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [ ]:
type(np.where(ar>5))

tuple

In [ ]:
np.count_nonzero(ar)

8

In [ ]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [ ]:
import sys

In [ ]:
py_ar= [0,4,55,'3a']

In [ ]:
np_ar=np.array(py_ar)

In [ ]:
sys.getsizeof(1) * len(py_ar)

112

In [ ]:
np_ar.itemsize * np_ar.size

176

In [ ]:
narr= np.array([1,2,3,'w'])

In [ ]:
narr

array(['1', '2', '3', 'w'], dtype='<U11')

In [ ]:
narr+narr

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> None